### ISSUE TITLE
[Feature]: Support for macOS arm64 (Apple Silicon)

### ISSUE THREAD

**Issue by cheekm** [KubeDeckio/KubeTidy#28]
## Summary

Support for Apple Silicon machines - macOS arm64

## Use Case

This will widen the support of KubeTidy Mac users beyond x86_64 machines

## Implementation Details

n/a

## Additional Context

n/a

**Comment by PixelRobots** [comment]
Hello,

Thanks for the suggestion.

Are you wanting to use the PowerShell module or the Krew plugin.

Have you tried to use the PowerShell module?  Did you get any errors? 

Thanks

**Comment by cheekm** [comment]
I will use the Krew plugin.

By the way, I was able to get it installed and running by changing the arch value in the downloaded KubeTidy.yaml from amd64 to arm64.

Matt


From: Richard Hooper ***@***.***>
Date: Friday, October 11, 2024 at 2:40 PM
To: PixelRobots/KubeTidy ***@***.***>
Cc: Cheek, Matthew ***@***.***>, Author ***@***.***>
Subject: Re: [PixelRobots/KubeTidy] [Feature]: Support for macOS arm64 (Apple Silicon) (Issue #28)

Hello,

Thanks for the suggestion.

Are you wanting to use the PowerShell module or the Krew plugin.

Have you tried to use the PowerShell module? Did you get any errors?

Thanks

**Comment by PixelRobots** [comment]
Thanks for confirming.

I have updated the kubeTidy.yaml file now and it gets populated into the release so you can use that for arm.


You can try this command to test:

```bash
# Fetch the latest release tag using GitHub's API
LATEST_VERSION=$(curl -s https://api.github.com/repos/KubeDeckio/KubeTidy/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')

# Download the KubeTidy.yaml file from the latest release
curl -H "Cache-Control: no-cache" -O https://github.com/PixelRobKubeDeckioots/KubeTidy/releases/download/$LATEST_VERSION/KubeTidy.yaml

# Install the plugin using the downloaded KubeTidy.yaml file
kubectl krew install --manifest="./KubeTidy.yaml"
```

Let me know how you get on please.

**Comment by cheekm** [comment]
I’ve upgraded KubeTidy (well, uninstall and reinstalled) and now it is failing. I see you removed the banner at 0.0.18. I was initially on 0.0.14.

Before upgrading:

$ kubectl kubetidy -kubeconfig "$HOME/.kube/config" -listclusters

██╗  ██╗██╗   ██╗██████╗ ███████╗████████╗██╗██████╗ ██╗   ██╗
██║ ██╔╝██║   ██║██╔══██╗██╔════╝╚══██╔══╝██║██╔══██╗╚██╗ ██╔╝
█████╔╝ ██║   ██║██████╔╝█████╗     ██║   ██║██║  ██║ ╚████╔╝
██╔═██╗ ██║   ██║██╔══██╗██╔══╝     ██║   ██║██║  ██║  ╚██╔╝
██║  ██╗╚██████╔╝██████╔╝███████╗   ██║   ██║██████╔╝   ██║
╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝   ╚═╝   ╚═╝╚═════╝    ╚═╝

Listing all clusters in KubeConfig file:

Cluster: api-acpd-xxxx.xxxx.xxx:6443
Cluster: api-arod-xxxx.xxxx.xxx:6443
Cluster: api-cpd-xxxx.xxxx.xxx:6443
Cluster: api-cpdr-xxxx.xxxx.xxx:6443
Cluster: api-cpp-xxxx.xxxx.xxx:6443
Cluster: api-cpsec-xxxx.xxxx.xxx:8443
Cluster: api-cpt-xxxx.xxxx.xxx:6443
Cluster: api-dev-ocp4-xxxx.xxxx.xxx:6443
Cluster: api-hub-ocp4-xxxx.xxxx.xxx:6443
Cluster: api-opshd-xxxx.xxxx.xxx:6443
Cluster: api-osacd-dev-xxxx.xxxx.xxx:6443
Cluster: api-osacd-sbx-xxxx.xxxx.xxx:6443
Cluster: api-osacp-xxxx.xxxx.xxx:6443
Cluster: api-osact-xxxx.xxxx.xxx:6443
Cluster: api-osazd-xxxx.xxxx.xxx:6443
Cluster: api-osazp-xxxx.xxxx.xxx:6443
Cluster: api-osazt-xxxx.xxxx.xxx:6443
Cluster: api-rhckp-xxxx.xxxx.xxx:6443
Cluster: api-sbx-ocp4-xxxx.xxxx.xxx:6443
Cluster: api-staging-xxxx.xxxx.xxx:6443
Cluster: api-tst-ocp4-xxxx.xxxx.xxx:6443
Cluster: console-cpsec-xxxx.xxxx.xxx:8443

Total Clusters: 22
$

Uninstall and reinstall:

$ kubectl krew uninstall kubetidy
Uninstalled plugin: kubetidy

$ LATEST_VERSION=$(curl -s https://api.github.com/repos/KubeDeckio/KubeTidy/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
$ echo $LATEST_VERSION
v0.0.18
curl -L -H "Cache-Control: no-cache" -O https://github.com/KubeDeckio/KubeTidy/releases/download/$LATEST_VERSION/KubeTidy.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1787  100  1787    0     0   4448      0 --:--:-- --:--:-- --:--:--  4448
$ ls -l ./KubeTidy.yaml
-rw-rw-r--@ 1 cheekm  staff  1787 Oct 27 12:03 ./KubeTidy.yaml
$ sum ./KubeTidy.yaml
4482 2 ./KubeTidy.yaml
$ kubectl krew install --manifest="./KubeTidy.yaml"
Installing plugin: kubetidy
Installed plugin: kubetidy
\
| Use this plugin:
|              kubectl kubetidy
| Documentation:
|              https://kubetidy.io
| Caveats:
| \
|  | **Requirements:**
|  | - PowerShell 7 or higher must be installed.
| /
/
$

$ kubectl krew list
PLUGIN             VERSION
detached/kubetidy  v0.0.18
krew               v0.4.4

$ kubectl kubetidy -kubeconfig "$HOME/.kube/config" --ListClusters
Get-AllClusters:
Line |
201 |          Get-AllClusters -KubeConfigPath $KubeConfigPath
     |          ~~~~~~~~~~~~~~~
     | The term 'Get-AllClusters' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

$ kubectl kubetidy -kubeconfig "$HOME/.kube/config" -Help

Parameters:
  -KubeConfigPath      Path to your kubeconfig file.
  -ExclusionList       Comma-separated list of clusters to exclude from cleanup.
  -Force               Force cleanup even if no clusters are reachable.
  -ListClusters        Display a list of all clusters in the kubeconfig file.
  -ListContexts        Display a list of all contexts in the kubeconfig file.
  -ExportContexts      Comma-separated list of contexts to export from the kubeconfig.
  -MergeConfigs        Array of kubeconfig files to merge.
  -DestinationConfig   Path to save the merged or exported kubeconfig file.
  -DryRun              Simulate the cleanup process without making changes.
  -Help                Display this help message.
$ kubectl kubetidy -kubeconfig "$HOME/.kube/config" -ListContexts
Get-KubeContexts:
Line |
207 |          Get-KubeContexts -KubeConfigPath $KubeConfigPath
     |          ~~~~~~~~~~~~~~~~
     | The term 'Get-KubeContexts' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
$

Is it me?



From: Richard Hooper ***@***.***>
Date: Thursday, October 17, 2024 at 10:29 AM
To: KubeDeckio/KubeTidy ***@***.***>
Cc: Cheek, Matthew ***@***.***>, Author ***@***.***>
Subject: Re: [KubeDeckio/KubeTidy] [Feature]: Support for macOS arm64 (Apple Silicon) (Issue #28)

Thanks for confirming.

I have updated the kubeTidy.yaml file now and it gets populated into the release so you can use that for arm.

You can try this command to test:

# Fetch the latest release tag using GitHub's API

LATEST_VERSION=$(curl -s https://api.github.com/repos/KubeDeckio/KubeTidy/releases/latest<https://urldefense.com/v3/__https:/api.github.com/repos/KubeDeckio/KubeTidy/releases/latest__;!!NHLzug!JbG4LGMl2RRmjLH-REANs29Px_GYJvFw65tzMIcsjelCKT5Wk9QyZF_JM6CjRUKngvE_N2MeSeKKEfk57Rn-oVI$> | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')



# Download the KubeTidy.yaml file from the latest release

curl -H "Cache-Control: no-cache" -O https://github.com/PixelRobKubeDeckioots/KubeTidy/releases/download/<https://urldefense.com/v3/__https:/github.com/PixelRobKubeDeckioots/KubeTidy/releases/download/__;!!NHLzug!JbG4LGMl2RRmjLH-REANs29Px_GYJvFw65tzMIcsjelCKT5Wk9QyZF_JM6CjRUKngvE_N2MeSeKKEfk5HgzKCU0$>$LATEST_VERSION/KubeTidy.yaml



# Install the plugin using the downloaded KubeTidy.yaml file

kubectl krew install --manifest="./KubeTidy.yaml"

Let me know how you get on please.

**Comment by PixelRobots** [comment]
Hello,

I have done another Update to fix the . sourcing of the modules used by the code.

Can you test again with the newest version please.

If it fails, could you try again with the -Verbose paramater and share the output.

As I do not own a mac device, I will start to look at ways to test using GitHub actions to ensure this does not happen again.

**Comment by cheekm** [comment]
This KubeTidy v0.0.20 is working again:


MacBook-Air[/Users/cheekm] LATEST_VERSION=$(curl -s https://api.github.com/repos/KubeDeckio/KubeTidy/releases/latest | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
MacBook-Air[/Users/cheekm] echo $LATEST_VERSION
v0.0.20
MacBook-Air[/Users/cheekm] curl -L -H "Cache-Control: no-cache" -O https://github.com/KubeDeckio/KubeTidy/releases/download/$LATEST_VERSION/KubeTidy.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1787  100  1787    0     0   5134      0 --:--:-- --:--:-- --:--:--  5134
MacBook-Air[/Users/cheekm] kubectl krew uninstall kubetidy
Uninstalled plugin: kubetidy
MacBook-Air[/Users/cheekm] kubectl krew install --manifest="./KubeTidy.yaml"
Installing plugin: kubetidy
Installed plugin: kubetidy
\
| Use this plugin:
|              kubectl kubetidy
| Documentation:
|              https://kubetidy.io
| Caveats:
| \
|  | **Requirements:**
|  | - PowerShell 7 or higher must be installed.
| /
/
MacBook-Air[/Users/cheekm] kubectl kubetidy -kubeconfig "$HOME/.kube/config" -help

Parameters:
  -KubeConfigPath      Path to your kubeconfig file.
  -ExclusionList       Comma-separated list of clusters to exclude from cleanup.
  -Force               Force cleanup even if no clusters are reachable.
  -ListClusters        Display a list of all clusters in the kubeconfig file.
  -ListContexts        Display a list of all contexts in the kubeconfig file.
  -ExportContexts      Comma-separated list of contexts to export from the kubeconfig.
  -MergeConfigs        Array of kubeconfig files to merge.
  -DestinationConfig   Path to save the merged or exported kubeconfig file.
  -DryRun              Simulate the cleanup process without making changes.
  -Help                Display this help message.
MacBook-Air[/Users/cheekm] kubectl kubetidy -kubeconfig "$HOME/.kube/config" -ListClusters

██╗  ██╗██╗   ██╗██████╗ ███████╗████████╗██╗██████╗ ██╗   ██╗
██║ ██╔╝██║   ██║██╔══██╗██╔════╝╚══██╔══╝██║██╔══██╗╚██╗ ██╔╝
█████╔╝ ██║   ██║██████╔╝█████╗     ██║   ██║██║  ██║ ╚████╔╝
██╔═██╗ ██║   ██║██╔══██╗██╔══╝     ██║   ██║██║  ██║  ╚██╔╝
██║  ██╗╚██████╔╝██████╔╝███████╗   ██║   ██║██████╔╝   ██║
╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝   ╚═╝   ╚═╝╚═════╝    ╚═╝

Listing all clusters in KubeConfig file:

Cluster: api-acpd-xxx-xxxx-xxx:6443
Cluster: api-arod-xxx-xxxx-xxx:6443
Cluster: api-cpd-xxx-xxxx-xxx:6443
Cluster: api-cpdr-xxx-xxxx-xxx:6443
Cluster: api-cpp-xxx-xxxx-xxx:6443
Cluster: api-cpsec-xxx-xxxx-xxx:8443
Cluster: api-cpt-xxx-xxxx-xxx:6443
Cluster: api-dev-ocp4-xxx-xxxx-xxx:6443
Cluster: api-hub-ocp4-xxx-xxxx-xxx:6443
Cluster: api-opshd-xxx-xxxx-xxx:6443
Cluster: api-osacd-dev-xxx-xxxx-xxx:6443
Cluster: api-osacd-sbx-xxx-xxxx-xxx:6443
Cluster: api-osacp-xxx-xxxx-xxx:6443
Cluster: api-osact-xxx-xxxx-xxx:6443
Cluster: api-osazd-xxx-xxxx-xxx:6443
Cluster: api-osazp-xxx-xxxx-xxx:6443
Cluster: api-osazt-xxx-xxxx-xxx:6443
Cluster: api-rhckp-xxx-xxxx-xxx:6443
Cluster: api-sbx-ocp4-xxx-xxxx-xxx:6443
Cluster: api-staging-xxx-xxxx-xxx:6443
Cluster: api-tst-ocp4-xxx-xxxx-xxx:6443
Cluster: console-cpsec-xxx-xxxx-xxx:8443

Total Clusters: 22
MacBook-Air[/Users/cheekm]


I would be happy to help with any testing.

Thanks,
Matt


From: Richard Hooper ***@***.***>
Date: Tuesday, October 29, 2024 at 9:24 AM
To: KubeDeckio/KubeTidy ***@***.***>
Cc: Cheek, Matthew ***@***.***>, Author ***@***.***>
Subject: Re: [KubeDeckio/KubeTidy] [Feature]: Support for macOS arm64 (Apple Silicon) (Issue #28)

Hello,

I have done another Update to fix the . sourcing of the modules used by the code.

Can you test again with the newest version please.

If it fails, could you try again with the -Verbose paramater and share the output.

As I do not own a mac device, I will start to look at ways to test using GitHub actions to ensure this does not happen again.

**Comment by PixelRobots** [comment]
Good to hear. Thanks for checking and thanks for your offer of helping with testing :).

I will go ahead and close this issue now. Any other issues or ideas, please open a new issue.

Thanks
